### ISSUE TITLE
Any way to modify for CircuitPython?

### ISSUE THREAD

**Issue by geekinchief2021** [KitronikLtd/Kitronik-Pico-Robotics-Board-MicroPython#1]
Are there any simple changes I could make to the library so I can use it in CircuitPython rather than MicroPython?

**Comment by DaveAtKitronik** [comment]
Hi,
Sorry for the delay - I was on leave.  
I have created a Circuit Python version here: https://github.com/KitronikLtd/Kitronik-Pico-Robotics-Board-CircuitPython

Dave
